In [2]:
import json
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
import pandas as pd
import torch

In [ ]:
pad_token_id = 0
targets = torch.tensor([4,7,0,0,2,0])

mask = targets == pad_token_id

tensor([4, 7, 0, 0, 2, 0])

In [4]:
mask

tensor([False, False,  True,  True, False,  True])

In [7]:
indices = torch.nonzero(mask).squeeze()
indices

tensor([2, 3, 5])

In [8]:
if indices.numel() > 1:
    targets[indices[1:]] = - 100

In [9]:
targets

tensor([   4,    7,    0, -100,    2, -100])